### ISSUE TITLE
Nozzle crash after performing Z_TILT_ADJUST with the Eddy coil

### ISSUE THREAD

**Issue by cssi-dev** [krautech/btt-eddy-guide#10]
I tried printing the first part after switching to the new probe. I was suprised to learn, that my print was canceled during the print start macro.
Error: 
> probe triggered prior to movement

with `horizontal_move_z: 5 `

So I switched it to `horizontal_move_z: 10`(even though In the bed section the horizontal_move_z is just 2 ), to then get the nozzle crash because the printer after getting all the readings moved all z axes way to far.

I get that you are not supposed to use the eddy coil for homing because of the temprature drift. But please let us use the Tilt adjust. I don't want to switch every 5-10 prints between the probes just to readjust the z axis when it gets out of wack.

Steps to reproduce:
1. Home the Printer
2. Start `Z_TILT_ADJUST`
3. Be ready to shutdown the printer befor something bad happens
[klippy.log](https://github.com/user-attachments/files/16666768/klippy.log)

**Comment by krautech** [comment]
Please refer to 

[BTT Eddy](https://github.com/bigtreetech/Eddy)

For up to date information

**Comment by cssi-dev** [comment]
You mean move this Issue to the other repo?

**Comment by krautech** [comment]
Yeah it'll get more attention over there.

This repo was setup when I first built the guide before it was adopted by BTT. It's maintained on their official repo now.

Instructions etc have changed which could also solve some issues

**Comment by cssi-dev** [comment]
Ok, thank you
