### ISSUE TITLE
Support for Kamp Adaptive Meshing

### ISSUE THREAD

**Issue by Travis90x** [krautech/btt-eddy-guide#4]
Edit your [Adaptive_Meshing.cfg](https://github.com/Travis90x/Klipper-Adaptive-Meshing-Purging)
   
 {% if printer.configfile.config['probe_eddy_current btt_eddy'] is not defined %} 
    _BED_MESH_CALIBRATE mesh_min={adapted_x_min},{adapted_y_min} mesh_max={adapted_x_max},{adapted_y_max} ALGORITHM={algorithm} PROBE_COUNT={points_x},{points_y}
    {% else %}
    M118 BTT Eddy detected
    _BED_MESH_CALIBRATE mesh_min={adapted_x_min},{adapted_y_min} mesh_max={adapted_x_max},{adapted_y_max} ALGORITHM={algorithm} PROBE_COUNT={points_x},{points_y} METHOD=scan SCAN_MODE=rapid
    {% endif %}

**Comment by krautech** [comment]
I did consider this. I even suggested it to a few people myself, but honestly running KAMP isn't worth it when it's natively in klipper now and it requires no extra configuration etc. 

On the off-chance people DO want to use KAMP, I will add this to the guide 👍 

Thank you
