### ISSUE TITLE
Removing KAMP not 100% necessary. Adaptive Purge still works

### ISSUE THREAD

**Issue by thomasfjen** [krautech/btt-eddy-guide#5]
![grafik](https://github.com/krautech/vyper-klipper/assets/47940833/4fbe77d5-3039-4476-b19b-bc9712918076)

You mention in your guide that KAMP should be removed. That's not entirely correct, you simply shouldn't use the meshing part anymore and rely on the klipper adaptive one, like you mentioned. 

You still can use the purge part without any problems. 

![grafik](https://github.com/krautech/vyper-klipper/assets/47940833/efc78938-239f-424b-96b7-20d9a5e37602)

**Comment by krautech** [comment]
You are indeed correct, I shall update this now.

**Comment by krautech** [comment]
You are indeed correct, I will update this now, thank you

**Comment by krautech** [comment]
The guide has been updated :) thank you!
